version: 1.0.{build}
configuration: Release
environment:
  COVERALLS_REPO_TOKEN:
    secure: BBNg3VStxwYHdGWSAqD80VTZHlTb6jViMPz4+MtH5yl0P/g5zK+kcUt0F0wYbqKJ
before_build:
- nuget restore
build:
  verbosity: minimal
  project: AspNetMvcSerialization.sln
test_script:
- ps: .\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:$env:xunit20\xunit.console.exe "-targetargs:"".\tests\AspNetMvcSerialization.Tests\bin\$env:CONFIGURATION\AspNetMvcSerialization.Tests.dll"" -noshadow -appveyor" -filter:"+[AspNetMvcSerialization*]*" -output:coverage.xml
- ps: .\packages\coveralls.net.0.6.0\tools\csmacnz.Coveralls.exe --opencover -i coverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --useRelativePaths --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID